### ISSUE TITLE
Retornando valor para cep inexistente (Ex.: 55555-555)

### ISSUE THREAD

**Issue by xnog** [vitorleal/node-correios#14]
Retornando valor para cep inexistente (Ex.: 55555-555)

**Comment by vitorleal** [comment]
Não consigo reproduzir.

<img width="267" alt="screen shot 2016-01-23 at 1 37 35 pm" src="https://cloud.githubusercontent.com/assets/438651/12530972/881d93ce-c1d6-11e5-82aa-456c3c986616.png">

**Comment by xnog** [comment]
Desculpe Vitor, é no método de calcular frete e prazo.

**Comment by xnog** [comment]
http://correios-server.herokuapp.com/frete/prazo?nCdServico=40010,40045&sCepOrigem=22041030&sCepDestino=55555555&nVlPeso=1&nCdFormato=1&nVlComprimento=20&nVlAltura=4&nVlLargura=11&nVlDiametro=20&nVlValorDeclarado=500

**Comment by vitorleal** [comment]
Infelizmente este retorno é da api dos correios. Não temos como tratar pois retorna sem nenhum conteúdo no **MsgErro: { }**

**Comment by xnog** [comment]
O estranho é que se eu fizer o teste no site dos correios ele nao retorna isso.

Emfim, será necessário fazer 2 chamadas, verificar cep e depois, caso sucesso, consultar preço e prazo.

**Comment by vitorleal** [comment]
Isso acho que fica a parte do desenvolvedor fazer na aplicação dele, a biblioteca retorna o conteúdo do webserver dos correios sem tratamento.
