### ISSUE TITLE
consultaCEP não funciona?

### ISSUE THREAD

**Issue by fabiancarlos** [vitorleal/node-correios#16]
Opa, a consulta de CEP depende obviamente de uma webservice externa né, mas faz dias que não esta mais funcionando, procede??

**Comment by vitorleal** [comment]
Oi @fabiancarlos, parece que o serviço de CEP parou de funcionar mesmo. Vou procurar outro para poder integrar e atualizar a lib.

**Comment by EduhCosta** [comment]
Tô com o mesmo erro man, demora cerca de 1min a requisição e depois ela para, o serviço não está respondendo e o HTTP response vem com 503.

Alguma modificação???

**Comment by vitorleal** [comment]
Não teve modificação, tem que verificar se a API do correios está de pé.

**Comment by EduhCosta** [comment]
Foi a API dos correios mesmo man.
Tudo ok.

**Comment by vitorleal** [comment]
Beleza, infelizmente acontece com certa constância.

Abraços

**Comment by PauloBoaventura** [comment]
Infelizmente apos abrir mais de 45 chamados em todos projetos que usam....
Vejo que o problema não é só dos correios.
As taxas mais uma vez mudaram de valor.... Agora os correios tem Seguro. O que esta gerando um calculo errado diante da consulta antiga. 
E assim entendo os os desenvolvedores,  que optaram por não se desgastar em atualizar ou melhor refazer o trabalho do zero.  Com tantas mudanças e diversos problemas..
O que achei uma boa opção é trabalhar com Tabela. E colocar mais de uma opção para o cliente.
Dá trabalho, mas não tem tanta dor de cabeça...
Estou desenvolvendo uma implementação que funciona com tabela, consulta os correios e atualiza transportadoras. 
Me desafiei a fazer este trabalho, cansativo afim de ter uma tranquilidade.
Espero que em breve possa compartilhar. Para ajudar a muitos.

As extensões de vocês estão funcionado?
E quais são estas?
Gostaria de saber se estão efetuando o valor correto... 

Abraços
