### ISSUE TITLE
Dúvidas (2018)

### ISSUE THREAD

**Issue by PauloBoaventura** [vitorleal/node-correios#25]
Este código esta funcionando em PHP 5, 5.6, 7.0, 7.1 ou até mesmo em 7.2 ?
São muitas dúvidas e nada pessoal... (Já deixo claro)
Este código esta nas normativas novas dos correios (2017) e que pelo visto já existe novas normativas em (2018)...
Bom, este não é o único que visualizamos que aparentemente esta tudo correto.
Mas, tenho que ser este USUÁRIO questionador, já que estamos enfrentando tantos problemas seja eles em PHP, AJAX ou qualquer impulso anterior á 2017.
E assim vem as dúvidas...

Gostaria de saber se podemos implementar este código em outras ferramentas e até mesmo em outas plataformas... 

Espero que tenhamos uma resposta satisfatória e um UPGRADE.

**Comment by vitorleal** [comment]
Boa tarde Paulo.
Infelizmente esse módulo não é para PHP.

Esse módulo e para NodeJS (https://nodejs.org) por isso o nome **node**-correios. E pode ser instalado utilizando o NPM.

Esse módulo funciona encima da API SOAP dos correios.

Abraços

**Comment by PauloBoaventura** [comment]
Olá @vitorleal entendi...
Teria alguma alternativa para ser usado em Magento 1.9 ou 2.1 ??

Obrigado pela atenção!
Abraços!

**Comment by vitorleal** [comment]
Não trabalho com Magento Paulo, mas buscando aqui no Github achei esse https://github.com/pedro-teixeira/correios espero que te ajude.

Abraços

**Comment by PauloBoaventura** [comment]
Olá @vitorleal 
Este projeto do #PedroTeixeira Não tem qualquer atualização desde 2017 e qualquer informação a respeito... 
Mas irei buscar algo que seja eficaz!
Obrigado desde já pela contribuição!

**Comment by PauloBoaventura** [comment]
#16 https://github.com/vitorleal/node-correios/issues/16#issuecomment-391517442
