### ISSUE TITLE
Sistema de Cache

### ISSUE THREAD

**Issue by ThalesMatoso** [vitorleal/node-correios#26]
Existe algum tipo de cache feito nesse modulo? digo não precisar ir no correios devido as condições atender um cache seja la (Redis, memcached, ...) ?

Digo isso por que estou precisando de trabalhar um cache do correios para melhorar a performance da resposta final, levando em consideração que faço consumo no correios e outras transportadoras..

**Comment by vitorleal** [comment]
Oi Thales,
o módulo não realiza cache.

Imagino que o lugar mais apropriado para o cache seria na própria aplicação e não no módulo.

Abraços
