### ISSUE TITLE
Possibilidade de enviar array de objetos

### ISSUE THREAD

**Issue by igordeoliveirasa** [vitorleal/node-correios#30]
Ola, parabéns pela biblioteca. Estou usando em um sistema que estou desenvolvendo. No entanto, para calcular o cep do carrinho de compras eu preciso mantar item a item e somar os resultados. É possível enviar todos os items de uma vez só e receber já um array de todos eles?

Obrigado!

**Comment by vitorleal** [comment]
Oi Igor. Como esse modelo não é aceito pelos Correios não tem uma implementação nesse modelo na biblioteca.

Minha sugestão para você e usar um Promisse.all ou algo do tipo para esperar o resultado de todos os itens antes de atualizar a interface.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
