### ISSUE TITLE
Update SOAP module

### ISSUE THREAD

**Issue by diogoviannaaraujo** [vitorleal/node-correios#31]
Hi, there are multiple vulnerabilities reported when installing your package. All of them are sub dependencies of the SOAP module.

An update on SOAP version would fix that, would that be possible?

Thanks

**Comment by LuizHonorato** [comment]
Same problem here. It's possible??

**Comment by vitorleal** [comment]
Yes, im preparing the update

**Comment by LuizHonorato** [comment]
Nice! I'm following you!

Thanks!

Em ter, 6 de ago de 2019 21:30, Vitor Leal <notifications@github.com>
escreveu:
