### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by LuizHonorato** [vitorleal/node-correios#36]
Boa noite.

Estou recebendo o seguinte erro ao referenciar a biblioteca no meu projeto:

Could not find a declaration file for module 'node-correios'. '~/node_modules/node-correios/index.js' implicitly has an 'any' type.
  Try `npm install @types/node-correios` if it exists or add a new declaration (.d.ts) file containing `declare module 'node-correios';

Esse é um erro da biblioteca ou é algum problema no meu ambiente??

Estou utilizando em um projeto com Laravel 5.8 e VueJS,
Node Version: 8.16.0
NPM version: 6.10.3

Atenciosamente,
Luiz Honorato

**Comment by vitorleal** [comment]
Bom dia, pelo que parece você está usando TypeScript. A lib não esta escrita em TypeScript por isso acho que ele está reclamando que não acha nenhum tipo nela. 

No StackOverflow (https://stackoverflow.com/questions/41292559/could-not-find-a-declaration-file-for-module-module-name-path-to-module-nam/41307319) tem algumas sugestões que tentam resolver esse problema no seu ambiente.

Espero que ajude.

Abs
