### ISSUE TITLE
Internacional

### ISSUE THREAD

**Issue by wubuyun** [vitorleal/node-correios#38]
Pretente coloca modulo leve internacional e ems no futuro ?

**Comment by vitorleal** [comment]
Oi @wubuyun, se tiver a documentação para essas integrações me passa que eu dou uma olhada e quando tiver um tempo eu insiro.

Abs,

**Comment by wubuyun** [comment]
https://cws2.correios.com.br/static/swagger/?url=/precoprazoservice/rs/swagger.json#/
