### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by irvingsl** [vitorleal/node-correios#40]
Vitor, obrigado pela excelente API. Estou tendo problemas pra usá-la no Heroku, acredito que seja devido aos requests HTTPS, o viacep não os recebe. Faz ideia de algum método de conversão? Se me der alguma luz eu posso submeter um PR, se achar interessante.

**Comment by irvingsl** [comment]
Na verdade, o Heroku faz a requisição adicionando :80 depois do endereço, o que acaba dando errado. Eu testei internalizando a lib e setando a cepURL como https e não http, assim o Heroku não fez nenhuma mudança e continuou funcionando em localhost, o viacep aceita sim https...

**Comment by Theeeus** [comment]
@irvingsl, também estou tendo problemas com o Heroku. Você pode me dar uma luz em qual foi a solução que você encontrou?
