### ISSUE TITLE
Erro: Erro inesperado. Descrição: Máximo de 1 código de serviço por consulta.

### ISSUE THREAD

**Issue by marcos93net** [vitorleal/node-correios#41]
Olá, não está dando para consultar mais de um serviço (Pac, Sedex). Só está dando pra consultar apenas 1. Se eu coloco os códigos dos produtos separados por virgula dá esse erro: "Erro inesperado. Descrição: Máximo de 1 código de serviço por consulta.". Poderia me ajudar?

**Comment by lucabarbosa** [comment]
Estou com o mesmo erro. Conseguiu corrigir, @marcos93net ?

**Comment by marcos93net** [comment]
@lucabarbosa eu estava olhando na doc dos correios e percebi que estava faltando dois parâmetros. Coloquei eles e resolveu! nCdEmpresa=08082650&sDsSenha=564321
