### ISSUE TITLE
Método caclPrecoPrazo não funciona com multiplos nCdServico

### ISSUE THREAD

**Issue by RodrigoHBD** [vitorleal/node-correios#42]
Estou tentando fazer uma consulta em vários tipos de entrega, conforme a documentação, porém o correios responde com um erro dizendo que só pode um por requisição. Exelente módulo entretanto, parabéns

**Comment by RodrigoHBD** [comment]
`valores pra requisição do correio { nCdServico: '04014,04065,04510,04707,40169,40215,40290',
  sCepOrigem: '81410370',
  sCepDestino: '04180112',
  nVlPeso: '8kg',
  nCdFormato: 1,
  nVlComprimento: 100,
  nVlAltura: 90,
  nVlLargura: 90,
  nVlDiametro: 150 }
Fretagem: [ { Codigo: 0,
    Valor: '0',
    PrazoEntrega: '0',
    ValorMaoPropria: '0',
    ValorAvisoRecebimento: '0',
    ValorValorDeclarado: '0',
    EntregaDomiciliar: '',
    EntregaSabado: '',
    Erro: '99',
    MsgErro:
     'Erro inesperado. Descrição: Máximo de 1 código de serviço por consulta.',
    ValorSemAdicionais: '0',
    obsFim: '' } ]`

**Comment by lucabarbosa** [comment]
@RodrigoHBD, dá uma olhada na issue #41 que acredito que resolverá seu problema!
