### ISSUE TITLE
Requisição cross-origin bloqueada

### ISSUE THREAD

**Issue by srwonka** [vitorleal/node-correios#47]

**Comment by rbueno** [comment]
Olá. Como você resolveu esse problema? Abs

**Comment by srwonka** [comment]
Eu estava chamando o método de minha máquina, localmente. Quando ele faz
isso, o browser não permite o acesso ao webservice. Então, para testes,
instalei a extensão "allow cross domain" no Firefox e deu tudo certo.

Em qui, 19 de nov de 2020 00:38, Rafael Bueno <notifications@github.com>
escreveu:
