### ISSUE TITLE
Error with consultaCEP

### ISSUE THREAD

**Issue by guilhermedecampo** [vitorleal/node-correios#8]
Hi @vitorleal thanks for the awesome package!

I think something is wrong with `correios.consultaCEP`.

I'm receiving this error:

```
TypeError: Cannot call method 'consultaCEP' of undefined
```

Precisely in this line: https://github.com/vitorleal/node-correios/blob/master/lib/correios.js#L123 
Although `correios.calcPreco`is working just fine.

Do you have any thoughts on how I would be able to fix this?
Thanks

**Comment by vitorleal** [comment]
Look's like the search for CEP server is down :rage4: 

I will take a better look and try to find an alternative.

Cheers

**Comment by guilhermedecampo** [comment]
Can we use JSON instead of SOAP?

**Comment by vitorleal** [comment]
Unfortunately the Brazilian Correio's  is a **shi@#!$** and the only option they provide to calculate the shipment prices is this SOAP service.

The CEP search i was using was not from Correio's, it was made from someone and they probably was scrapping the Correios [search page](http://www.buscacep.correios.com.br/).

I don't like SOAP at all but we can only move on to migrate is to a better solution when the start to modernize their services.

I will use this option to keep the ```buscaCEP``` method in the API but if this **AvisoBrasil** comes down it will happen again.

**Comment by guilhermedecampo** [comment]
Ok cool, I'll keep up posted if something goes wrong with this AvisoBrasil.

Do you need some help to do the change?

Thanks!

**Comment by vitorleal** [comment]
Thanks,
no need i will push the changes latter today :smile: 

Thanks for the heads up!
